navbar
msalvatore82/api-front pull request #1
Opened 2023-07-15 11:38 UTC by msalvatore82

2023-07-15 11:53 UTC, JonaTheBridge requested changes

2023-07-15 11:53 UTC, JonaTheBridge commented on src/AppRouter.jsx
> +      },
este objeto quitalo, que lo subo yo en mi PR. Deja solo el de abajo

2023-07-15 11:53 UTC, JonaTheBridge commented on src/assets/43568.jpg
este jpg al final lo vamos a usar??

2023-07-15 11:53 UTC, JonaTheBridge commented on src/assets/43568.svg
este svg al final lo vamos a usar??

2023-07-15 11:53 UTC, JonaTheBridge commented on src/components/Navbar/Navbar.jsx
aquí hay muchísimas clases, son de bootstrap?? no tengo ni idea de lo que hacen xD

2023-07-15 11:53 UTC, JonaTheBridge commented on src/pages/Landing/Landing.css
> +
añade una linea en blanco al final del fichero para quitar el símbolo feo este de prohibido

2023-07-15 11:53 UTC, JonaTheBridge commented on src/pages/Landing/Landing.jsx
> +export default Landing;
añade una linea en blanco al final del fichero para quitar el símbolo feo este de prohibido

2023-07-15 11:53 UTC, JonaTheBridge commented on src/pages/Landing/Landing.jsx
> +import logo from '../../assets/logo.png'
tenemos que decidir si meter las imágenes y eso en la carpeta public o en assets, pero intentemos no usar las dos, no le veo sentido

2023-07-17 16:14 UTC, msalvatore82 commented on src/components/Navbar/Navbar.jsx
yesss bootstrap

2023-07-17 17:14 UTC, JonaTheBridge approved these changes

2023-07-17 17:14 UTC, merged